// The captive-portal page, served by provision.c at http://192.168.4.1/. Kept static (lives in
// flash, sent without copying); current values come from /config.json and the network list from
// /scan, so nothing is templated on the device. No external resources: the phone has no
// internet while it is on the TVTOP-xxxx network.
#pragma once

static const char portal_html[] =
"<!doctype html><html><head><meta charset=utf-8>"
"<meta name=viewport content='width=device-width,initial-scale=1'>"
"<title>TV-Top Kiosk setup</title>"
"<style>"
"body{margin:0;background:#101418;color:#e8ecf0;font:16px/1.4 system-ui,sans-serif}"
"main{max-width:420px;margin:0 auto;padding:24px 16px}"
"h1{font-size:22px;margin:0 0 4px}p{margin:0 0 18px;color:#9aa4ae}"
"label{display:block;margin:14px 0 4px;font-size:13px;color:#9aa4ae}"
"input,select{width:100%;box-sizing:border-box;padding:11px 12px;border-radius:8px;"
"border:1px solid #2c343c;background:#181e24;color:#e8ecf0;font-size:16px}"
".row{display:flex;gap:8px}.row input{flex:1}"
"button{padding:11px 16px;border:0;border-radius:8px;background:#2c343c;color:#e8ecf0;font-size:16px}"
"button.p{background:#3b82f6;width:100%;margin-top:22px;font-weight:600}"
"#msg{margin-top:14px;min-height:22px;color:#f6c343}"
"</style></head><body><main>"
"<h1>TV-Top Kiosk</h1><p id=sub>Connect this kiosk to your Wi-Fi.</p>"
"<form id=f method=post action=/save>"
"<label for=ssid>Wi-Fi network</label>"
"<div class=row><input id=ssid name=ssid list=nets maxlength=32 required autocomplete=off>"
"<button type=button id=scan>Scan</button></div><datalist id=nets></datalist>"
"<label for=pass>Password (leave empty for an open network)</label>"
"<input id=pass name=pass type=password maxlength=64 autocomplete=off>"
"<label for=server>Kiosk server</label>"
"<input id=server name=server maxlength=255 placeholder='https://kiosk.tvtop.games'>"
"<label for=mode>Video mode</label>"
#if KIOSK_HSTX
"<select id=mode name=mode><option value=720p60>1280x720 60 Hz</option><option value=960x540p60>960x540 60 Hz</option><option value=480p60>640x480 60 Hz</option><option value=1080p30>1920x1080 30 Hz</option><option value=1080p25>1920x1080 25 Hz (TV)</option><option value=1080p24>1920x1080 24 Hz (TV)</option></select>"
#else
"<select id=mode name=mode><option value=960x540p60>960x540 60 Hz</option><option value=1066x600p50>1066x600 50 Hz</option>"
"<option value=720x480p60>720x480 60 Hz</option>"
"<option value=720p30>1280x720 30 Hz</option>"
"<option value=720p30rb>1280x720 30 Hz (reduced blanking)</option>"
"<option value=480p60>640x480 60 Hz</option></select>"
#endif
"<button class=p type=submit>Save and reboot</button>"
"<div id=msg></div></form></main>"
"<script>"
"var $=function(i){return document.getElementById(i)};"
"fetch('/config.json').then(function(r){return r.json()}).then(function(c){"
"$('ssid').value=c.ssid||'';$('server').value=c.server||'';var m=$('mode');if(c.mode&&![].some.call(m.options,function(o){return o.value==c.mode})){var o=document.createElement('option');o.value=o.textContent=c.mode;m.appendChild(o)}if(c.mode)m.value=c.mode;"
"$('sub').textContent='Kiosk '+c.ap+' \\u00b7 firmware '+c.fw;}).catch(function(){});"
"var polls=0;function poll(){fetch('/scan').then(function(r){return r.json()}).then(function(l){"
"var d=$('nets');d.innerHTML='';l.sort(function(a,b){return b.rssi-a.rssi}).forEach(function(n){"
"var o=document.createElement('option');o.value=n.ssid;o.label=n.ssid+' ('+n.rssi+' dBm'+(n.open?', open':'')+')';d.appendChild(o)});"
"$('msg').textContent=l.length?l.length+' networks found':'Scanning\\u2026';"
"if(++polls<6)setTimeout(poll,1500);else $('scan').disabled=false;}).catch(function(){$('scan').disabled=false})}"
"$('scan').onclick=function(){polls=0;$('scan').disabled=true;poll()};"
"$('f').onsubmit=function(e){e.preventDefault();var p=$('pass').value;"
"if(p.length&&p.length<8){$('msg').textContent='A WPA2 password has at least 8 characters.';return}"
"$('msg').textContent='Saving\\u2026';"
"fetch('/save',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},"
"body:new URLSearchParams(new FormData($('f'))).toString()}).then(function(r){return r.text()})"
".then(function(t){$('msg').textContent=t}).catch(function(){$('msg').textContent='Saved. The kiosk is rebooting; you can close this page.'})};"
"</script></body></html>";
