cmake_minimum_required(VERSION 3.13)
set(PICO_BOARD pico_w CACHE STRING "")
if (NOT DEFINED ENV{PICO_SDK_PATH} AND NOT PICO_SDK_PATH)
    set(PICO_SDK_PATH "$ENV{HOME}/.pico-sdk/sdk/2.2.0")
endif()
if (NOT DEFINED ENV{PICO_TOOLCHAIN_PATH} AND NOT PICO_TOOLCHAIN_PATH)
    set(PICO_TOOLCHAIN_PATH "$ENV{HOME}/.pico-sdk/toolchain/arm-gnu-toolchain-15.3.rel1-darwin-arm64-arm-none-eabi")
endif()
include(pico_sdk_import.cmake)
project(pin_test C CXX ASM)
pico_sdk_init()
add_executable(pin_test main.c)
target_link_libraries(pin_test pico_stdlib hardware_adc)
pico_enable_stdio_usb(pin_test 1)
pico_enable_stdio_uart(pin_test 0)
pico_add_extra_outputs(pin_test)
